// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents any kind of non-wildcard ID, including IDs of embedded objects.
 */
public class AnyId {
    @JsonValue
    private String value;

    public AnyId() {
    }

    @JsonCreator
    public AnyId(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
