// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded AssetCollectionId that can be used to match multiple
 * AssetCollection objects.
 */
public class AssetCollectionIdWildcard {
    @JsonValue
    private String value;

    public AssetCollectionIdWildcard() {
    }

    @JsonCreator
    public AssetCollectionIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
