// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A reference to the value of an asset control.
 */
public enum AssetControlValueRefUsing {
    @JsonProperty("asset_control")
    ASSET_CONTROL,
}
