// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A basic counter representing a non-rollable integer value. They usually start
 * at 0, and may or may not have a maximum.
 */
@JsonSerialize
public class AssetAbilityControlFieldCounter extends AssetAbilityControlField {
    @JsonProperty("label")
    private Label label;

    @JsonProperty("max")
    private Short max;

    @JsonProperty("min")
    private Byte min;

    @JsonProperty("rollable")
    private Boolean rollable;

    @JsonProperty("value")
    private Byte value;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("icon")
    private SvgImageUrl icon;

    public AssetAbilityControlFieldCounter() {
    }

    /**
     * Getter for label.<p>
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     */
    public void setLabel(Label label) {
        this.label = label;
    }

    /**
     * Getter for max.<p>
     */
    public Short getMax() {
        return max;
    }

    /**
     * Setter for max.<p>
     */
    public void setMax(Short max) {
        this.max = max;
    }

    /**
     * Getter for min.<p>
     * The (inclusive) minimum value.
     */
    public Byte getMin() {
        return min;
    }

    /**
     * Setter for min.<p>
     * The (inclusive) minimum value.
     */
    public void setMin(Byte min) {
        this.min = min;
    }

    /**
     * Getter for rollable.<p>
     */
    public Boolean getRollable() {
        return rollable;
    }

    /**
     * Setter for rollable.<p>
     */
    public void setRollable(Boolean rollable) {
        this.rollable = rollable;
    }

    /**
     * Getter for value.<p>
     * The current value of this input.
     */
    public Byte getValue() {
        return value;
    }

    /**
     * Setter for value.<p>
     * The current value of this input.
     */
    public void setValue(Byte value) {
        this.value = value;
    }

    /**
     * Getter for icon.<p>
     * An icon associated with this input.
     */
    public SvgImageUrl getIcon() {
        return icon;
    }

    /**
     * Setter for icon.<p>
     * An icon associated with this input.
     */
    public void setIcon(SvgImageUrl icon) {
        this.icon = icon;
    }
}
