// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded AssetAbilityMoveId that can be used to match multiple
 * AssetAbilityMove objects.
 */
public class AssetAbilityMoveIdWildcard {
    @JsonValue
    private String value;

    public AssetAbilityMoveIdWildcard() {
    }

    @JsonCreator
    public AssetAbilityMoveIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
