// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded AssetAbilityOracleRollableId that can be used to match multiple
 * AssetAbilityOracleRollable objects.
 */
public class AssetAbilityOracleRollableIdWildcard {
    @JsonValue
    private String value;

    public AssetAbilityOracleRollableIdWildcard() {
    }

    @JsonCreator
    public AssetAbilityOracleRollableIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
