// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A clock with 4 or more segments.
 */
@JsonSerialize
public class AssetAbilityControlFieldClock extends AssetAbilityControlField {
    @JsonProperty("label")
    private Label label;

    @JsonProperty("max")
    private Byte max;

    @JsonProperty("min")
    private Byte min;

    @JsonProperty("rollable")
    private Boolean rollable;

    @JsonProperty("value")
    private Byte value;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("icon")
    private SvgImageUrl icon;

    public AssetAbilityControlFieldClock() {
    }

    /**
     * Getter for label.<p>
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     */
    public void setLabel(Label label) {
        this.label = label;
    }

    /**
     * Getter for max.<p>
     * The size of the clock -- in other words, the maximum number of filled
     * clock segments. Standard clocks have 4, 6, 8, or 10 segments.
     */
    public Byte getMax() {
        return max;
    }

    /**
     * Setter for max.<p>
     * The size of the clock -- in other words, the maximum number of filled
     * clock segments. Standard clocks have 4, 6, 8, or 10 segments.
     */
    public void setMax(Byte max) {
        this.max = max;
    }

    /**
     * Getter for min.<p>
     * The minimum number of filled clock segments. This is always 0.
     */
    public Byte getMin() {
        return min;
    }

    /**
     * Setter for min.<p>
     * The minimum number of filled clock segments. This is always 0.
     */
    public void setMin(Byte min) {
        this.min = min;
    }

    /**
     * Getter for rollable.<p>
     */
    public Boolean getRollable() {
        return rollable;
    }

    /**
     * Setter for rollable.<p>
     */
    public void setRollable(Boolean rollable) {
        this.rollable = rollable;
    }

    /**
     * Getter for value.<p>
     * The current value of this input.
     */
    public Byte getValue() {
        return value;
    }

    /**
     * Setter for value.<p>
     * The current value of this input.
     */
    public void setValue(Byte value) {
        this.value = value;
    }

    /**
     * Getter for icon.<p>
     * An icon associated with this input.
     */
    public SvgImageUrl getIcon() {
        return icon;
    }

    /**
     * Setter for icon.<p>
     * An icon associated with this input.
     */
    public void setIcon(SvgImageUrl icon) {
        this.icon = icon;
    }
}
