// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum AtlasEntryType {
    @JsonProperty("atlas_entry")
    ATLAS_ENTRY,
}
