// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A reference to the value of an attached asset option.
 */
public enum AttachedAssetOptionValueRefUsing {
    @JsonProperty("attached_asset_option")
    ATTACHED_ASSET_OPTION,
}
