// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum CollectableType {
    @JsonProperty("asset")
    ASSET,

    @JsonProperty("atlas_entry")
    ATLAS_ENTRY,

    @JsonProperty("move")
    MOVE,

    @JsonProperty("npc")
    NPC,

    @JsonProperty("oracle_rollable")
    ORACLE_ROLLABLE,
}
