// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum CollectionType {
    @JsonProperty("asset_collection")
    ASSET_COLLECTION,

    @JsonProperty("atlas_collection")
    ATLAS_COLLECTION,

    @JsonProperty("move_category")
    MOVE_CATEGORY,

    @JsonProperty("npc_collection")
    NPC_COLLECTION,

    @JsonProperty("oracle_collection")
    ORACLE_COLLECTION,
}
