// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A reference to the value of a standard player condition meter.
 */
@JsonSerialize
public class ConditionMeterValueRef {
    @JsonProperty("condition_meter")
    private ConditionMeterKey conditionMeter;

    @JsonProperty("using")
    private ConditionMeterValueRefUsing using;

    public ConditionMeterValueRef() {
    }

    /**
     * Getter for conditionMeter.<p>
     */
    public ConditionMeterKey getConditionMeter() {
        return conditionMeter;
    }

    /**
     * Setter for conditionMeter.<p>
     */
    public void setConditionMeter(ConditionMeterKey conditionMeter) {
        this.conditionMeter = conditionMeter;
    }

    /**
     * Getter for using.<p>
     * A reference to the value of a standard player condition meter.
     */
    public ConditionMeterValueRefUsing getUsing() {
        return using;
    }

    /**
     * Setter for using.<p>
     * A reference to the value of a standard player condition meter.
     */
    public void setUsing(ConditionMeterValueRefUsing using) {
        this.using = using;
    }
}
