// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A reference to the value of a standard player condition meter.
 */
public enum ConditionMeterValueRefUsing {
    @JsonProperty("condition_meter")
    CONDITION_METER,
}
