// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An arbitrary static integer value with a label.
 */
public enum CustomValueUsing {
    @JsonProperty("custom")
    CUSTOM,
}
