// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded DelveSiteThemeFeatureId that can be used to match multiple
 * DelveSiteThemeFeature objects.
 */
public class DelveSiteThemeFeatureIdWildcard {
    @JsonValue
    private String value;

    public DelveSiteThemeFeatureIdWildcard() {
    }

    @JsonCreator
    public DelveSiteThemeFeatureIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
