// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded DelveSiteThemeDangerId that can be used to match multiple
 * DelveSiteThemeDanger objects.
 */
public class DelveSiteThemeDangerIdWildcard {
    @JsonValue
    private String value;

    public DelveSiteThemeDangerIdWildcard() {
    }

    @JsonCreator
    public DelveSiteThemeDangerIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
