// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;
import java.util.Map;

/**
 * A delve site with a theme, domain, and denizens.
 */
@JsonSerialize
public class DelveSite {
    @JsonProperty("_id")
    private DelveSiteId id;

    @JsonProperty("_source")
    private SourceInfo source;

    @JsonProperty("denizens")
    private List<DelveSiteDenizen> denizens;

    @JsonProperty("description")
    private MarkdownString description;

    @JsonProperty("domain")
    private DelveSiteDomainId domain;

    @JsonProperty("name")
    private Label name;

    @JsonProperty("rank")
    private ChallengeRank rank;

    @JsonProperty("theme")
    private DelveSiteThemeId theme;

    @JsonProperty("type")
    private DelveSiteType type;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("_comment")
    private String comment;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("canonical_name")
    private Label canonicalName;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("extra_card")
    private String extraCard;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("icon")
    private SvgImageUrl icon;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("region")
    private AtlasEntryId region;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("suggestions")
    private Suggestions suggestions;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("tags")
    private Map<String, Map<String, Tag>> tags;

    public DelveSite() {
    }

    /**
     * Getter for id.<p>
     * The unique Datasworn ID for this item.
     */
    public DelveSiteId getId() {
        return id;
    }

    /**
     * Setter for id.<p>
     * The unique Datasworn ID for this item.
     */
    public void setId(DelveSiteId id) {
        this.id = id;
    }

    /**
     * Getter for source.<p>
     * Attribution for the original source (such as a book or website) of this
     * item, including the author and licensing information.
     */
    public SourceInfo getSource() {
        return source;
    }

    /**
     * Setter for source.<p>
     * Attribution for the original source (such as a book or website) of this
     * item, including the author and licensing information.
     */
    public void setSource(SourceInfo source) {
        this.source = source;
    }

    /**
     * Getter for denizens.<p>
     * Represents the delve site's denizen matrix as an array of objects.
     */
    public List<DelveSiteDenizen> getDenizens() {
        return denizens;
    }

    /**
     * Setter for denizens.<p>
     * Represents the delve site's denizen matrix as an array of objects.
     */
    public void setDenizens(List<DelveSiteDenizen> denizens) {
        this.denizens = denizens;
    }

    /**
     * Getter for description.<p>
     */
    public MarkdownString getDescription() {
        return description;
    }

    /**
     * Setter for description.<p>
     */
    public void setDescription(MarkdownString description) {
        this.description = description;
    }

    /**
     * Getter for domain.<p>
     * The ID of the site's DelveSiteDomain card.
     */
    public DelveSiteDomainId getDomain() {
        return domain;
    }

    /**
     * Setter for domain.<p>
     * The ID of the site's DelveSiteDomain card.
     */
    public void setDomain(DelveSiteDomainId domain) {
        this.domain = domain;
    }

    /**
     * Getter for name.<p>
     * The primary name/label for this item.
     */
    public Label getName() {
        return name;
    }

    /**
     * Setter for name.<p>
     * The primary name/label for this item.
     */
    public void setName(Label name) {
        this.name = name;
    }

    /**
     * Getter for rank.<p>
     */
    public ChallengeRank getRank() {
        return rank;
    }

    /**
     * Setter for rank.<p>
     */
    public void setRank(ChallengeRank rank) {
        this.rank = rank;
    }

    /**
     * Getter for theme.<p>
     * The ID of the site's DelveSiteTheme card.
     */
    public DelveSiteThemeId getTheme() {
        return theme;
    }

    /**
     * Setter for theme.<p>
     * The ID of the site's DelveSiteTheme card.
     */
    public void setTheme(DelveSiteThemeId theme) {
        this.theme = theme;
    }

    /**
     * Getter for type.<p>
     */
    public DelveSiteType getType() {
        return type;
    }

    /**
     * Setter for type.<p>
     */
    public void setType(DelveSiteType type) {
        this.type = type;
    }

    /**
     * Getter for comment.<p>
     * Any implementation hints or other developer-facing comments on this
     * object. These should be omitted when presenting the object for gameplay.
     */
    public String getComment() {
        return comment;
    }

    /**
     * Setter for comment.<p>
     * Any implementation hints or other developer-facing comments on this
     * object. These should be omitted when presenting the object for gameplay.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for canonicalName.<p>
     * The name of this item as it appears on the page in the book, if it's
     * different from `name`.
     */
    public Label getCanonicalName() {
        return canonicalName;
    }

    /**
     * Setter for canonicalName.<p>
     * The name of this item as it appears on the page in the book, if it's
     * different from `name`.
     */
    public void setCanonicalName(Label canonicalName) {
        this.canonicalName = canonicalName;
    }

    /**
     * Getter for extraCard.<p>
     * An additional theme or domain card ID, for use with optional rules in
     * Ironsworn: Delve.
     */
    public String getExtraCard() {
        return extraCard;
    }

    /**
     * Setter for extraCard.<p>
     * An additional theme or domain card ID, for use with optional rules in
     * Ironsworn: Delve.
     */
    public void setExtraCard(String extraCard) {
        this.extraCard = extraCard;
    }

    /**
     * Getter for icon.<p>
     */
    public SvgImageUrl getIcon() {
        return icon;
    }

    /**
     * Setter for icon.<p>
     */
    public void setIcon(SvgImageUrl icon) {
        this.icon = icon;
    }

    /**
     * Getter for region.<p>
     * The ID of an atlas entry representing the region in which this delve site
     * is located.
     */
    public AtlasEntryId getRegion() {
        return region;
    }

    /**
     * Setter for region.<p>
     * The ID of an atlas entry representing the region in which this delve site
     * is located.
     */
    public void setRegion(AtlasEntryId region) {
        this.region = region;
    }

    /**
     * Getter for suggestions.<p>
     */
    public Suggestions getSuggestions() {
        return suggestions;
    }

    /**
     * Setter for suggestions.<p>
     */
    public void setSuggestions(Suggestions suggestions) {
        this.suggestions = suggestions;
    }

    /**
     * Getter for tags.<p>
     */
    public Map<String, Map<String, Tag>> getTags() {
        return tags;
    }

    /**
     * Setter for tags.<p>
     */
    public void setTags(Map<String, Map<String, Tag>> tags) {
        this.tags = tags;
    }
}
