// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded DelveSiteDomainFeatureId that can be used to match multiple
 * DelveSiteDomainFeature objects.
 */
public class DelveSiteDomainFeatureIdWildcard {
    @JsonValue
    private String value;

    public DelveSiteDomainFeatureIdWildcard() {
    }

    @JsonCreator
    public DelveSiteDomainFeatureIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
