// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded DelveSiteId that can be used to match multiple DelveSite
 * objects.
 */
public class DelveSiteIdWildcard {
    @JsonValue
    private String value;

    public DelveSiteIdWildcard() {
    }

    @JsonCreator
    public DelveSiteIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
