// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded DelveSiteDomainDangerId that can be used to match multiple
 * DelveSiteDomainDanger objects.
 */
public class DelveSiteDomainDangerIdWildcard {
    @JsonValue
    private String value;

    public DelveSiteDomainDangerIdWildcard() {
    }

    @JsonCreator
    public DelveSiteDomainDangerIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
