// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "oracle_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "column_text", value = EmbeddedOracleRollableColumnText.class),
    @JsonSubTypes.Type(name = "column_text2", value = EmbeddedOracleRollableColumnText2.class),
    @JsonSubTypes.Type(name = "column_text3", value = EmbeddedOracleRollableColumnText3.class),
    @JsonSubTypes.Type(name = "table_text", value = EmbeddedOracleRollableTableText.class),
    @JsonSubTypes.Type(name = "table_text2", value = EmbeddedOracleRollableTableText2.class),
    @JsonSubTypes.Type(name = "table_text3", value = EmbeddedOracleRollableTableText3.class),
})
public abstract class EmbeddedOracleRollable {
}
