// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * This type is a placeholder and may see signficant changes in v0.2.0.
 */
@JsonSerialize
public class EntityPrompt {
    @JsonProperty("text")
    private MarkdownString text;

    public EntityPrompt() {
    }

    /**
     * Getter for text.<p>
     */
    public MarkdownString getText() {
        return text;
    }

    /**
     * Setter for text.<p>
     */
    public void setText(MarkdownString text) {
        this.text = text;
    }
}
