// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Internationalization/localization hints for the text content of this object.
 */
@JsonSerialize
public class I18nHints {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("description")
    private I18nHint description;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("detail")
    private I18nHint detail;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("result")
    private I18nHint result;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("template")
    private I18nHintsTemplate template;

    public I18nHints() {
    }

    /**
     * Getter for description.<p>
     */
    public I18nHint getDescription() {
        return description;
    }

    /**
     * Setter for description.<p>
     */
    public void setDescription(I18nHint description) {
        this.description = description;
    }

    /**
     * Getter for detail.<p>
     */
    public I18nHint getDetail() {
        return detail;
    }

    /**
     * Setter for detail.<p>
     */
    public void setDetail(I18nHint detail) {
        this.detail = detail;
    }

    /**
     * Getter for result.<p>
     */
    public I18nHint getResult() {
        return result;
    }

    /**
     * Setter for result.<p>
     */
    public void setResult(I18nHint result) {
        this.result = result;
    }

    /**
     * Getter for template.<p>
     */
    public I18nHintsTemplate getTemplate() {
        return template;
    }

    /**
     * Setter for template.<p>
     */
    public void setTemplate(I18nHintsTemplate template) {
        this.template = template;
    }
}
