// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class I18nHintsTemplate {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("text")
    private I18nHint text;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("text2")
    private I18nHint text2;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("text3")
    private I18nHint text3;

    public I18nHintsTemplate() {
    }

    /**
     * Getter for text.<p>
     */
    public I18nHint getText() {
        return text;
    }

    /**
     * Setter for text.<p>
     */
    public void setText(I18nHint text) {
        this.text = text;
    }

    /**
     * Getter for text2.<p>
     */
    public I18nHint getText2() {
        return text2;
    }

    /**
     * Setter for text2.<p>
     */
    public void setText2(I18nHint text2) {
        this.text2 = text2;
    }

    /**
     * Getter for text3.<p>
     */
    public I18nHint getText3() {
        return text3;
    }

    /**
     * Setter for text3.<p>
     */
    public void setText3(I18nHint text3) {
        this.text3 = text3;
    }
}
