// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A localized, player-facing name or label, formatted as plain text. In some
 * contexts it may be undesirable to render this text, but it should always be
 * exposed to assistive technology (e.g. with `aria-label` in HTML).
 */
public class Label {
    @JsonValue
    private String value;

    public Label() {
    }

    @JsonCreator
    public Label(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
