// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded MoveOracleRollableRowId that can be used to match multiple
 * MoveOracleRollableRow objects.
 */
public class MoveOracleRollableRowIdWildcard {
    @JsonValue
    private String value;

    public MoveOracleRollableRowIdWildcard() {
    }

    @JsonCreator
    public MoveOracleRollableRowIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
