// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "roll_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "action_roll", value = MoveActionRoll0.class),
    @JsonSubTypes.Type(name = "no_roll", value = MoveNoRoll0.class),
    @JsonSubTypes.Type(name = "progress_roll", value = MoveProgressRoll0.class),
    @JsonSubTypes.Type(name = "special_track", value = MoveSpecialTrack0.class),
})
public abstract class Move {
}
