// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * An object that describes changes to a move. These changes should be applied
 * recursively, altering only the specified properties; enhanced arrays should
 * be concatencated with the original array value.
 */
@JsonSerialize
public class MoveProgressRollEnhancement {
    @JsonProperty("enhances")
    private List<AnyMoveIdWildcard> enhances;

    @JsonProperty("roll_type")
    private MoveProgressRollEnhancementRollType rollType;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("trigger")
    private TriggerProgressRollEnhancement trigger;

    public MoveProgressRollEnhancement() {
    }

    /**
     * Getter for enhances.<p>
     */
    public List<AnyMoveIdWildcard> getEnhances() {
        return enhances;
    }

    /**
     * Setter for enhances.<p>
     */
    public void setEnhances(List<AnyMoveIdWildcard> enhances) {
        this.enhances = enhances;
    }

    /**
     * Getter for rollType.<p>
     * A move must have this `roll_type` to receive this enhancement. This is in
     * addition to any other restrictions made by other properties.
     */
    public MoveProgressRollEnhancementRollType getRollType() {
        return rollType;
    }

    /**
     * Setter for rollType.<p>
     * A move must have this `roll_type` to receive this enhancement. This is in
     * addition to any other restrictions made by other properties.
     */
    public void setRollType(MoveProgressRollEnhancementRollType rollType) {
        this.rollType = rollType;
    }

    /**
     * Getter for trigger.<p>
     */
    public TriggerProgressRollEnhancement getTrigger() {
        return trigger;
    }

    /**
     * Setter for trigger.<p>
     */
    public void setTrigger(TriggerProgressRollEnhancement trigger) {
        this.trigger = trigger;
    }
}
