// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum NonCollectableType {
    @JsonProperty("delve_site")
    DELVE_SITE,

    @JsonProperty("delve_site_domain")
    DELVE_SITE_DOMAIN,

    @JsonProperty("delve_site_theme")
    DELVE_SITE_THEME,

    @JsonProperty("rarity")
    RARITY,

    @JsonProperty("truth")
    TRUTH,
}
