// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded NpcCollectionId that can be used to match multiple NpcCollection
 * objects.
 */
public class NpcCollectionIdWildcard {
    @JsonValue
    private String value;

    public NpcCollectionIdWildcard() {
    }

    @JsonCreator
    public NpcCollectionIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
