// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded NpcVariantId that can be used to match multiple NpcVariant
 * objects.
 */
public class NpcVariantIdWildcard {
    @JsonValue
    private String value;

    public NpcVariantIdWildcard() {
    }

    @JsonCreator
    public NpcVariantIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
