// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum OracleColumn2textCellsOracleType {
    @JsonProperty("column_text2")
    COLUMN_TEXT2,
}
