// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum OracleTableText3OracleType {
    @JsonProperty("table_text3")
    TABLE_TEXT3,
}
