// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "oracle_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "table_shared_details", value = OracleCollectionTableSharedDetails.class),
    @JsonSubTypes.Type(name = "table_shared_results", value = OracleCollectionTableSharedResults.class),
    @JsonSubTypes.Type(name = "table_shared_rolls", value = OracleCollectionTableSharedRolls.class),
    @JsonSubTypes.Type(name = "tables", value = OracleCollectionTables.class),
})
public abstract class OracleCollection {
}
