// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Special roll instructions to use when rolling multiple times on a single
 * oracle.
 */
public enum OracleDuplicateBehavior {
    /**
     * Duplicates results should be kept.
     */
    @JsonProperty("keep")
    KEEP,

    /**
     * Duplicates should be kept, and they compound to make things worse.
     */
    @JsonProperty("make_it_worse")
    MAKE_IT_WORSE,

    /**
     * Duplicates results should be re-rolled.
     */
    @JsonProperty("reroll")
    REROLL,
}
