// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "oracle_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "table_shared_rolls", value = OracleCollectionTableSharedRolls.class),
    @JsonSubTypes.Type(name = "table_shared_text", value = OracleCollectionTableSharedText.class),
    @JsonSubTypes.Type(name = "table_shared_text2", value = OracleCollectionTableSharedText2.class),
    @JsonSubTypes.Type(name = "table_shared_text3", value = OracleCollectionTableSharedText3.class),
    @JsonSubTypes.Type(name = "tables", value = OracleCollectionTables.class),
})
public abstract class OracleCollection {
}
