// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum OracleTableSharedText2OracleType {
    @JsonProperty("table_shared_text2")
    TABLE_SHARED_TEXT2,
}
