// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A table with multiple unique roll columns, and 3 shared text columns.
 */
public enum OracleTableSharedText3OracleType {
    @JsonProperty("table_shared_text3")
    TABLE_SHARED_TEXT3,
}
