// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded OracleRollableRowId that can be used to match multiple
 * OracleRollableRow objects.
 */
public class OracleRollableRowIdWildcard {
    @JsonValue
    private String value;

    public OracleRollableRowIdWildcard() {
    }

    @JsonCreator
    public OracleRollableRowIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
