// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * The label at the head of each table column. The `roll` key refers to the roll
 * column showing the dice range (`min` and `max` on each table row).
 */
@JsonSerialize
public class OracleCollectionTableSharedResultsColumnLabels {
    @JsonProperty("result")
    private Label result;

    public OracleCollectionTableSharedResultsColumnLabels() {
    }

    /**
     * Getter for result.<p>
     */
    public Label getResult() {
        return result;
    }

    /**
     * Setter for result.<p>
     */
    public void setResult(Label result) {
        this.result = result;
    }
}
