// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * A collection of table rows from which random results may be rolled. This may
 * represent a standalone table, or a column in a larger table.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "oracle_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "column_text", value = OracleRollableColumnText.class),
    @JsonSubTypes.Type(name = "column_text2", value = OracleRollableColumnText2.class),
    @JsonSubTypes.Type(name = "column_text3", value = OracleRollableColumnText3.class),
    @JsonSubTypes.Type(name = "table_text", value = OracleRollableTableText.class),
    @JsonSubTypes.Type(name = "table_text2", value = OracleRollableTableText2.class),
    @JsonSubTypes.Type(name = "table_text3", value = OracleRollableTableText3.class),
})
public abstract class OracleRollable {
}
