// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class OracleTableRoll {
    @JsonProperty("auto")
    private Boolean auto;

    @JsonProperty("dice")
    private DiceExpression dice;

    @JsonProperty("duplicates")
    private OracleTableRollDuplicates duplicates;

    @JsonProperty("number_of_rolls")
    private Short numberOfRolls;

    @JsonProperty("oracle")
    private OracleTableId oracle;

    public OracleTableRoll() {
    }

    /**
     * Getter for auto.<p>
     * Both Ironsworn and Starforged explicitly recommend *against* rolling
     * all details at once. That said, some oracle results only provide useful
     * information once a secondary roll occurs, such as "Action + Theme".
     */
    public Boolean getAuto() {
        return auto;
    }

    /**
     * Setter for auto.<p>
     * Both Ironsworn and Starforged explicitly recommend *against* rolling
     * all details at once. That said, some oracle results only provide useful
     * information once a secondary roll occurs, such as "Action + Theme".
     */
    public void setAuto(Boolean auto) {
        this.auto = auto;
    }

    /**
     * Getter for dice.<p>
     */
    public DiceExpression getDice() {
        return dice;
    }

    /**
     * Setter for dice.<p>
     */
    public void setDice(DiceExpression dice) {
        this.dice = dice;
    }

    /**
     * Getter for duplicates.<p>
     * Special rules on how to handle duplicate results, when rolling multiple
     * times on this table.
     */
    public OracleTableRollDuplicates getDuplicates() {
        return duplicates;
    }

    /**
     * Setter for duplicates.<p>
     * Special rules on how to handle duplicate results, when rolling multiple
     * times on this table.
     */
    public void setDuplicates(OracleTableRollDuplicates duplicates) {
        this.duplicates = duplicates;
    }

    /**
     * Getter for numberOfRolls.<p>
     * The number of times to roll.
     */
    public Short getNumberOfRolls() {
        return numberOfRolls;
    }

    /**
     * Setter for numberOfRolls.<p>
     * The number of times to roll.
     */
    public void setNumberOfRolls(Short numberOfRolls) {
        this.numberOfRolls = numberOfRolls;
    }

    /**
     * Getter for oracle.<p>
     */
    public OracleTableId getOracle() {
        return oracle;
    }

    /**
     * Setter for oracle.<p>
     */
    public void setOracle(OracleTableId oracle) {
        this.oracle = oracle;
    }
}
