// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A table with one shared roll column, and multiple unique text columns.
 */
public enum OracleTableSharedRollsOracleType {
    @JsonProperty("table_shared_rolls")
    TABLE_SHARED_ROLLS,
}
