// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents a page number in a book.
 */
public class PageNumber {
    @JsonValue
    private Short value;

    public PageNumber() {
    }

    @JsonCreator
    public PageNumber(Short value) {
        this.value = value;
    }

    public Short getValue() {
        return value;
    }

    public void setValue(Short value) {
        this.value = value;
    }
}
