// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded RarityId that can be used to match multiple Rarity objects.
 */
public class RarityIdWildcard {
    @JsonValue
    private String value;

    public RarityIdWildcard() {
    }

    @JsonCreator
    public RarityIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
