// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The version of the Datasworn format used by this data.
 */
public enum RulesPackageExpansionDataswornVersion {
    @JsonProperty("0.1.0")
    DEFAULT_NAME,
}
