// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum SelectEnhancementFieldFieldType {
    @JsonProperty("select_enhancement")
    SELECT_ENHANCEMENT,
}
