// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Metadata describing the original source of this node
 */
@JsonSerialize
public class SourceInfo {
    @JsonProperty("authors")
    private List<AuthorInfo> authors;

    @JsonProperty("date")
    private OffsetDateTime date;

    @JsonProperty("license")
    private License license;

    @JsonProperty("title")
    private String title;

    @JsonProperty("url")
    private WebUrl url;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("page")
    private UnsignedShort page;

    public SourceInfo() {
    }

    /**
     * Getter for authors.<p>
     * Lists authors credited by the source material.
     */
    public List<AuthorInfo> getAuthors() {
        return authors;
    }

    /**
     * Setter for authors.<p>
     * Lists authors credited by the source material.
     */
    public void setAuthors(List<AuthorInfo> authors) {
        this.authors = authors;
    }

    /**
     * Getter for date.<p>
     * The date of the source documents's last update, formatted YYYY-MM-DD.
     * Required because it's used to determine whether the data needs updating.
     */
    public OffsetDateTime getDate() {
        return date;
    }

    /**
     * Setter for date.<p>
     * The date of the source documents's last update, formatted YYYY-MM-DD.
     * Required because it's used to determine whether the data needs updating.
     */
    public void setDate(OffsetDateTime date) {
        this.date = date;
    }

    /**
     * Getter for license.<p>
     */
    public License getLicense() {
        return license;
    }

    /**
     * Setter for license.<p>
     */
    public void setLicense(License license) {
        this.license = license;
    }

    /**
     * Getter for title.<p>
     * The title of the source document.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Setter for title.<p>
     * The title of the source document.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for url.<p>
     * A URL where the source document is available.
     */
    public WebUrl getUrl() {
        return url;
    }

    /**
     * Setter for url.<p>
     * A URL where the source document is available.
     */
    public void setUrl(WebUrl url) {
        this.url = url;
    }

    /**
     * Getter for page.<p>
     * The page number where this content is described in full.
     */
    public UnsignedShort getPage() {
        return page;
    }

    /**
     * Setter for page.<p>
     * The page number where this content is described in full.
     */
    public void setPage(UnsignedShort page) {
        this.page = page;
    }
}
