// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.List;

public class Suggestions {
    @JsonValue
    private List<AnyIdWildcard> value;

    public Suggestions() {
    }

    @JsonCreator
    public Suggestions(List<AnyIdWildcard> value) {
        this.value = value;
    }

    public List<AnyIdWildcard> getValue() {
        return value;
    }

    public void setValue(List<AnyIdWildcard> value) {
        this.value = value;
    }
}
