// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "value_type")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "asset", value = TagRuleAsset.class),
    @JsonSubTypes.Type(name = "asset_collection", value = TagRuleAssetCollection.class),
    @JsonSubTypes.Type(name = "atlas", value = TagRuleAtlas.class),
    @JsonSubTypes.Type(name = "atlas_entry", value = TagRuleAtlasEntry.class),
    @JsonSubTypes.Type(name = "boolean", value = TagRuleBoolean.class),
    @JsonSubTypes.Type(name = "delve_site", value = TagRuleDelveSite.class),
    @JsonSubTypes.Type(name = "delve_site_domain", value = TagRuleDelveSiteDomain.class),
    @JsonSubTypes.Type(name = "delve_site_theme", value = TagRuleDelveSiteTheme.class),
    @JsonSubTypes.Type(name = "enum", value = TagRuleEnum.class),
    @JsonSubTypes.Type(name = "integer", value = TagRuleInteger.class),
    @JsonSubTypes.Type(name = "move", value = TagRuleMove.class),
    @JsonSubTypes.Type(name = "move_category", value = TagRuleMoveCategory.class),
    @JsonSubTypes.Type(name = "npc", value = TagRuleNpc.class),
    @JsonSubTypes.Type(name = "npc_collection", value = TagRuleNpcCollection.class),
    @JsonSubTypes.Type(name = "oracle_collection", value = TagRuleOracleCollection.class),
    @JsonSubTypes.Type(name = "oracle_rollable", value = TagRuleOracleRollable.class),
    @JsonSubTypes.Type(name = "rarity", value = TagRuleRarity.class),
    @JsonSubTypes.Type(name = "truth", value = TagRuleTruth.class),
})
public abstract class TagRule {
}
