// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class TruthOption {
    @JsonProperty("description")
    private MarkdownString description;

    @JsonProperty("quest_starter")
    private MarkdownString questStarter;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("max")
    private Short max;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("min")
    private Short min;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("summary")
    private MarkdownString summary;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("table")
    private TruthOptionTable table;

    public TruthOption() {
    }

    /**
     * Getter for description.<p>
     */
    public MarkdownString getDescription() {
        return description;
    }

    /**
     * Setter for description.<p>
     */
    public void setDescription(MarkdownString description) {
        this.description = description;
    }

    /**
     * Getter for questStarter.<p>
     */
    public MarkdownString getQuestStarter() {
        return questStarter;
    }

    /**
     * Setter for questStarter.<p>
     */
    public void setQuestStarter(MarkdownString questStarter) {
        this.questStarter = questStarter;
    }

    /**
     * Getter for max.<p>
     */
    public Short getMax() {
        return max;
    }

    /**
     * Setter for max.<p>
     */
    public void setMax(Short max) {
        this.max = max;
    }

    /**
     * Getter for min.<p>
     */
    public Short getMin() {
        return min;
    }

    /**
     * Setter for min.<p>
     */
    public void setMin(Short min) {
        this.min = min;
    }

    /**
     * Getter for summary.<p>
     */
    public MarkdownString getSummary() {
        return summary;
    }

    /**
     * Setter for summary.<p>
     */
    public void setSummary(MarkdownString summary) {
        this.summary = summary;
    }

    /**
     * Getter for table.<p>
     * Represents a basic rollable oracle table with one roll column and one
     * text result column.
     */
    public TruthOptionTable getTable() {
        return table;
    }

    /**
     * Setter for table.<p>
     * Represents a basic rollable oracle table with one roll column and one
     * text result column.
     */
    public void setTable(TruthOptionTable table) {
        this.table = table;
    }
}
