// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * Represents a basic rollable oracle table with one roll column and one text
 * result column.
 */
@JsonSerialize
public class TruthOptionTable {
    @JsonProperty("dice")
    private DiceExpression dice;

    @JsonProperty("oracle_type")
    private TruthOptionTableOracleType oracleType;

    @JsonProperty("rows")
    private List<OracleTableRowText> rows;

    public TruthOptionTable() {
    }

    /**
     * Getter for dice.<p>
     * The roll used to select a result on this oracle.
     */
    public DiceExpression getDice() {
        return dice;
    }

    /**
     * Setter for dice.<p>
     * The roll used to select a result on this oracle.
     */
    public void setDice(DiceExpression dice) {
        this.dice = dice;
    }

    /**
     * Getter for oracleType.<p>
     */
    public TruthOptionTableOracleType getOracleType() {
        return oracleType;
    }

    /**
     * Setter for oracleType.<p>
     */
    public void setOracleType(TruthOptionTableOracleType oracleType) {
        this.oracleType = oracleType;
    }

    /**
     * Getter for rows.<p>
     * An array of objects, each representing a single row of the table.
     */
    public List<OracleTableRowText> getRows() {
        return rows;
    }

    /**
     * Setter for rows.<p>
     * An array of objects, each representing a single row of the table.
     */
    public void setRows(List<OracleTableRowText> rows) {
        this.rows = rows;
    }
}
