// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded TruthId that can be used to match multiple Truth objects.
 */
public class TruthIdWildcard {
    @JsonValue
    private String value;

    public TruthIdWildcard() {
    }

    @JsonCreator
    public TruthIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
