// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetCardFlipFieldFieldTypeJsonConverter))]
    public enum AssetCardFlipFieldFieldType
    {
        CardFlip,
    }
    public class AssetCardFlipFieldFieldTypeJsonConverter : JsonConverter<AssetCardFlipFieldFieldType>
    {
        public override AssetCardFlipFieldFieldType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "card_flip":
                    return AssetCardFlipFieldFieldType.CardFlip;
                default:
                    throw new ArgumentException(String.Format("Bad AssetCardFlipFieldFieldType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetCardFlipFieldFieldType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetCardFlipFieldFieldType.CardFlip:
                    JsonSerializer.Serialize<string>(writer, "card_flip", options);
                    return;
            }
        }
    }
}
