// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A reference to the value of an asset option.
    /// </summary>
    [JsonConverter(typeof(AssetOptionValueRefUsingJsonConverter))]
    public enum AssetOptionValueRefUsing
    {
        AssetOption,
    }
    public class AssetOptionValueRefUsingJsonConverter : JsonConverter<AssetOptionValueRefUsing>
    {
        public override AssetOptionValueRefUsing Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "asset_option":
                    return AssetOptionValueRefUsing.AssetOption;
                default:
                    throw new ArgumentException(String.Format("Bad AssetOptionValueRefUsing value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetOptionValueRefUsing value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetOptionValueRefUsing.AssetOption:
                    JsonSerializer.Serialize<string>(writer, "asset_option", options);
                    return;
            }
        }
    }
}
