// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A reference to the value of an asset option.
    /// </summary>
    public class AssetOptionValueRef
    {
        [JsonPropertyName("assets")]
        public IList<AssetIdWildcard> Assets { get; set; }

        /// <summary>
        /// The dictionary key of the asset option field.
        /// </summary>
        [JsonPropertyName("option")]
        public DictKey Option { get; set; }

        /// <summary>
        /// A reference to the value of an asset option.
        /// </summary>
        [JsonPropertyName("using")]
        public AssetOptionValueRefUsing Using { get; set; }
    }
}
