// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetCollectionTypeJsonConverter))]
    public enum AssetCollectionType
    {
        AssetCollection,
    }
    public class AssetCollectionTypeJsonConverter : JsonConverter<AssetCollectionType>
    {
        public override AssetCollectionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "asset_collection":
                    return AssetCollectionType.AssetCollection;
                default:
                    throw new ArgumentException(String.Format("Bad AssetCollectionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetCollectionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetCollectionType.AssetCollection:
                    JsonSerializer.Serialize<string>(writer, "asset_collection", options);
                    return;
            }
        }
    }
}
