// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded AssetAbilityMoveId that can be used to match multiple
    /// AssetAbilityMove objects.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityMoveIdWildcardJsonConverter))]
    public class AssetAbilityMoveIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityMoveIdWildcardJsonConverter : JsonConverter<AssetAbilityMoveIdWildcard>
    {
        public override AssetAbilityMoveIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityMoveIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityMoveIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
