// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetConditionMeterFieldTypeJsonConverter))]
    public enum AssetConditionMeterFieldType
    {
        ConditionMeter,
    }
    public class AssetConditionMeterFieldTypeJsonConverter : JsonConverter<AssetConditionMeterFieldType>
    {
        public override AssetConditionMeterFieldType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "condition_meter":
                    return AssetConditionMeterFieldType.ConditionMeter;
                default:
                    throw new ArgumentException(String.Format("Bad AssetConditionMeterFieldType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetConditionMeterFieldType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetConditionMeterFieldType.ConditionMeter:
                    JsonSerializer.Serialize<string>(writer, "condition_meter", options);
                    return;
            }
        }
    }
}
