// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A unique ID representing an AssetAbilityMove object.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityMoveIdJsonConverter))]
    public class AssetAbilityMoveId
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityMoveIdJsonConverter : JsonConverter<AssetAbilityMoveId>
    {
        public override AssetAbilityMoveId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityMoveId { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityMoveId value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
