// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded AssetAbilityOracleRollableRowId that can be used to match
    /// multiple AssetAbilityOracleRollableRow objects.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityOracleRollableRowIdWildcardJsonConverter))]
    public class AssetAbilityOracleRollableRowIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityOracleRollableRowIdWildcardJsonConverter : JsonConverter<AssetAbilityOracleRollableRowIdWildcard>
    {
        public override AssetAbilityOracleRollableRowIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityOracleRollableRowIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityOracleRollableRowIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
