// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AtlasCollectionTypeJsonConverter))]
    public enum AtlasCollectionType
    {
        AtlasCollection,
    }
    public class AtlasCollectionTypeJsonConverter : JsonConverter<AtlasCollectionType>
    {
        public override AtlasCollectionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "atlas_collection":
                    return AtlasCollectionType.AtlasCollection;
                default:
                    throw new ArgumentException(String.Format("Bad AtlasCollectionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AtlasCollectionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AtlasCollectionType.AtlasCollection:
                    JsonSerializer.Serialize<string>(writer, "atlas_collection", options);
                    return;
            }
        }
    }
}
