// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded AtlasCollectionId that can be used to match multiple
    /// AtlasCollection objects.
    /// </summary>
    [JsonConverter(typeof(AtlasCollectionIdWildcardJsonConverter))]
    public class AtlasCollectionIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AtlasCollectionIdWildcardJsonConverter : JsonConverter<AtlasCollectionIdWildcard>
    {
        public override AtlasCollectionIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AtlasCollectionIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AtlasCollectionIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
