// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AtlasEntryTypeJsonConverter))]
    public enum AtlasEntryType
    {
        AtlasEntry,
    }
    public class AtlasEntryTypeJsonConverter : JsonConverter<AtlasEntryType>
    {
        public override AtlasEntryType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "atlas_entry":
                    return AtlasEntryType.AtlasEntry;
                default:
                    throw new ArgumentException(String.Format("Bad AtlasEntryType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AtlasEntryType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AtlasEntryType.AtlasEntry:
                    JsonSerializer.Serialize<string>(writer, "atlas_entry", options);
                    return;
            }
        }
    }
}
