// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A reference to the value of an attached asset option.
    /// </summary>
    public class AttachedAssetOptionValueRef
    {
        /// <summary>
        /// The dictionary key of the asset option field.
        /// </summary>
        [JsonPropertyName("option")]
        public DictKey Option { get; set; }

        /// <summary>
        /// A reference to the value of an attached asset option.
        /// </summary>
        [JsonPropertyName("using")]
        public AttachedAssetOptionValueRefUsing Using { get; set; }
    }
}
