// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A reference to the value of an attached asset option.
    /// </summary>
    [JsonConverter(typeof(AttachedAssetOptionValueRefUsingJsonConverter))]
    public enum AttachedAssetOptionValueRefUsing
    {
        AttachedAssetOption,
    }
    public class AttachedAssetOptionValueRefUsingJsonConverter : JsonConverter<AttachedAssetOptionValueRefUsing>
    {
        public override AttachedAssetOptionValueRefUsing Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "attached_asset_option":
                    return AttachedAssetOptionValueRefUsing.AttachedAssetOption;
                default:
                    throw new ArgumentException(String.Format("Bad AttachedAssetOptionValueRefUsing value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AttachedAssetOptionValueRefUsing value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AttachedAssetOptionValueRefUsing.AttachedAssetOption:
                    JsonSerializer.Serialize<string>(writer, "attached_asset_option", options);
                    return;
            }
        }
    }
}
