// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(ConditionMeterFieldFieldTypeJsonConverter))]
    public enum ConditionMeterFieldFieldType
    {
        ConditionMeter,
    }
    public class ConditionMeterFieldFieldTypeJsonConverter : JsonConverter<ConditionMeterFieldFieldType>
    {
        public override ConditionMeterFieldFieldType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "condition_meter":
                    return ConditionMeterFieldFieldType.ConditionMeter;
                default:
                    throw new ArgumentException(String.Format("Bad ConditionMeterFieldFieldType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, ConditionMeterFieldFieldType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ConditionMeterFieldFieldType.ConditionMeter:
                    JsonSerializer.Serialize<string>(writer, "condition_meter", options);
                    return;
            }
        }
    }
}
