// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A reference to the value of a standard player condition meter.
    /// </summary>
    [JsonConverter(typeof(ConditionMeterValueRefUsingJsonConverter))]
    public enum ConditionMeterValueRefUsing
    {
        ConditionMeter,
    }
    public class ConditionMeterValueRefUsingJsonConverter : JsonConverter<ConditionMeterValueRefUsing>
    {
        public override ConditionMeterValueRefUsing Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "condition_meter":
                    return ConditionMeterValueRefUsing.ConditionMeter;
                default:
                    throw new ArgumentException(String.Format("Bad ConditionMeterValueRefUsing value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, ConditionMeterValueRefUsing value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ConditionMeterValueRefUsing.ConditionMeter:
                    JsonSerializer.Serialize<string>(writer, "condition_meter", options);
                    return;
            }
        }
    }
}
