// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// An arbitrary static integer value with a label.
    /// </summary>
    [JsonConverter(typeof(CustomValueUsingJsonConverter))]
    public enum CustomValueUsing
    {
        Custom,
    }
    public class CustomValueUsingJsonConverter : JsonConverter<CustomValueUsing>
    {
        public override CustomValueUsing Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "custom":
                    return CustomValueUsing.Custom;
                default:
                    throw new ArgumentException(String.Format("Bad CustomValueUsing value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, CustomValueUsing value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case CustomValueUsing.Custom:
                    JsonSerializer.Serialize<string>(writer, "custom", options);
                    return;
            }
        }
    }
}
