// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded DelveSiteDomainFeatureId that can be used to match multiple
    /// DelveSiteDomainFeature objects.
    /// </summary>
    [JsonConverter(typeof(DelveSiteDomainFeatureIdWildcardJsonConverter))]
    public class DelveSiteDomainFeatureIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class DelveSiteDomainFeatureIdWildcardJsonConverter : JsonConverter<DelveSiteDomainFeatureIdWildcard>
    {
        public override DelveSiteDomainFeatureIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DelveSiteDomainFeatureIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DelveSiteDomainFeatureIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
