// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an entry in a site denizen matrix. Denizen matrices are
    /// described in Ironsworn: Delve.
    /// </summary>
    public class DelveSiteDenizen
    {
        /// <summary>
        /// The unique Datasworn ID for this item.
        /// </summary>
        [JsonPropertyName("_id")]
        public DelveSiteDenizenId Id { get; set; }

        [JsonPropertyName("frequency")]
        public DelveSiteDenizenFrequency Frequency { get; set; }

        /// <summary>
        /// High end of the dice range for this denizen.
        /// </summary>
        [JsonPropertyName("max")]
        public short Max { get; set; }

        /// <summary>
        /// Low end of the dice range for this denizen.
        /// </summary>
        [JsonPropertyName("min")]
        public short Min { get; set; }

        /// <summary>
        /// Any implementation hints or other developer-facing comments on
        /// this object. These should be omitted when presenting the object
        /// for gameplay.
        /// </summary>
        [JsonPropertyName("_comment")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Comment { get; set; }

        /// <summary>
        /// A name for the denizen, if it's different than the `name` property
        /// of the NPC.
        /// </summary>
        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Label? Name { get; set; }

        /// <summary>
        /// The ID of the relevant NPC entry, if one is specified.
        /// </summary>
        [JsonPropertyName("npc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public NpcId? Npc { get; set; }
    }
}
