// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(DelveSiteTypeJsonConverter))]
    public enum DelveSiteType
    {
        DelveSite,
    }
    public class DelveSiteTypeJsonConverter : JsonConverter<DelveSiteType>
    {
        public override DelveSiteType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "delve_site":
                    return DelveSiteType.DelveSite;
                default:
                    throw new ArgumentException(String.Format("Bad DelveSiteType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, DelveSiteType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case DelveSiteType.DelveSite:
                    JsonSerializer.Serialize<string>(writer, "delve_site", options);
                    return;
            }
        }
    }
}
