// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded DelveSiteDomainId that can be used to match multiple
    /// DelveSiteDomain objects.
    /// </summary>
    [JsonConverter(typeof(DelveSiteDomainIdWildcardJsonConverter))]
    public class DelveSiteDomainIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class DelveSiteDomainIdWildcardJsonConverter : JsonConverter<DelveSiteDomainIdWildcard>
    {
        public override DelveSiteDomainIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DelveSiteDomainIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DelveSiteDomainIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
