// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A unique ID representing a DelveSiteThemeDanger object.
    /// </summary>
    [JsonConverter(typeof(DelveSiteThemeDangerIdJsonConverter))]
    public class DelveSiteThemeDangerId
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class DelveSiteThemeDangerIdJsonConverter : JsonConverter<DelveSiteThemeDangerId>
    {
        public override DelveSiteThemeDangerId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DelveSiteThemeDangerId { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DelveSiteThemeDangerId value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
