// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A unique ID representing a DelveSiteDomainDanger object.
    /// </summary>
    [JsonConverter(typeof(DelveSiteDomainDangerIdJsonConverter))]
    public class DelveSiteDomainDangerId
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class DelveSiteDomainDangerIdJsonConverter : JsonConverter<DelveSiteDomainDangerId>
    {
        public override DelveSiteDomainDangerId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DelveSiteDomainDangerId { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DelveSiteDomainDangerId value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
