// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an entry in a site denizen matrix. Denizen matrices are
    /// described in Ironsworn: Delve.
    /// </summary>
    public class DelveSiteDenizen
    {
        [JsonPropertyName("frequency")]
        public DelveSiteDenizenFrequency Frequency { get; set; }

        [JsonPropertyName("roll")]
        public DiceRange Roll { get; set; }

        /// <summary>
        /// A name for the denizen, if it's different than the `name` property
        /// of the NPC.
        /// </summary>
        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Label? Name { get; set; }

        /// <summary>
        /// The ID of the relevant NPC entry, if one is specified.
        /// </summary>
        [JsonPropertyName("npc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public NpcId? Npc { get; set; }
    }
}
