// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleRollableTableText2TypeJsonConverter))]
    public enum EmbeddedOracleRollableTableText2Type
    {
        OracleRollable,
    }
    public class EmbeddedOracleRollableTableText2TypeJsonConverter : JsonConverter<EmbeddedOracleRollableTableText2Type>
    {
        public override EmbeddedOracleRollableTableText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return EmbeddedOracleRollableTableText2Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleRollableTableText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleRollableTableText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleRollableTableText2Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
