// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedProgressRollMoveTypeJsonConverter))]
    public enum EmbeddedProgressRollMoveType
    {
        Move,
    }
    public class EmbeddedProgressRollMoveTypeJsonConverter : JsonConverter<EmbeddedProgressRollMoveType>
    {
        public override EmbeddedProgressRollMoveType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return EmbeddedProgressRollMoveType.Move;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedProgressRollMoveType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedProgressRollMoveType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedProgressRollMoveType.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
