// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleRollableJsonConverter))]
    public abstract class EmbeddedOracleRollable
    {
    }

    public class EmbeddedOracleRollableJsonConverter : JsonConverter<EmbeddedOracleRollable>
    {
        public override EmbeddedOracleRollable Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("oracle_type").GetString();

            switch (tagValue)
            {
                case "column_text":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableColumnText>(ref readerCopy, options);
                case "column_text2":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableColumnText2>(ref readerCopy, options);
                case "column_text3":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableColumnText3>(ref readerCopy, options);
                case "table_text":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableTableText>(ref readerCopy, options);
                case "table_text2":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableTableText2>(ref readerCopy, options);
                case "table_text3":
                    return JsonSerializer.Deserialize<EmbeddedOracleRollableTableText3>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad OracleType value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleRollable value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
