// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleColumnTextOracleTypeJsonConverter))]
    public enum EmbeddedOracleColumnTextOracleType
    {
        ColumnText,
    }
    public class EmbeddedOracleColumnTextOracleTypeJsonConverter : JsonConverter<EmbeddedOracleColumnTextOracleType>
    {
        public override EmbeddedOracleColumnTextOracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "column_text":
                    return EmbeddedOracleColumnTextOracleType.ColumnText;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleColumnTextOracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleColumnTextOracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleColumnTextOracleType.ColumnText:
                    JsonSerializer.Serialize<string>(writer, "column_text", options);
                    return;
            }
        }
    }
}
