// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedActionRollMoveTypeJsonConverter))]
    public enum EmbeddedActionRollMoveType
    {
        Move,
    }
    public class EmbeddedActionRollMoveTypeJsonConverter : JsonConverter<EmbeddedActionRollMoveType>
    {
        public override EmbeddedActionRollMoveType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return EmbeddedActionRollMoveType.Move;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedActionRollMoveType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedActionRollMoveType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedActionRollMoveType.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
