// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleTableTextOracleTypeJsonConverter))]
    public enum EmbeddedOracleTableTextOracleType
    {
        TableText,
    }
    public class EmbeddedOracleTableTextOracleTypeJsonConverter : JsonConverter<EmbeddedOracleTableTextOracleType>
    {
        public override EmbeddedOracleTableTextOracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "table_text":
                    return EmbeddedOracleTableTextOracleType.TableText;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleTableTextOracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleTableTextOracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleTableTextOracleType.TableText:
                    JsonSerializer.Serialize<string>(writer, "table_text", options);
                    return;
            }
        }
    }
}
