// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleTableText2TypeJsonConverter))]
    public enum EmbeddedOracleTableText2Type
    {
        OracleRollable,
    }
    public class EmbeddedOracleTableText2TypeJsonConverter : JsonConverter<EmbeddedOracleTableText2Type>
    {
        public override EmbeddedOracleTableText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return EmbeddedOracleTableText2Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleTableText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleTableText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleTableText2Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
