// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedNoRollMoveRollTypeJsonConverter))]
    public enum EmbeddedNoRollMoveRollType
    {
        NoRoll,
    }
    public class EmbeddedNoRollMoveRollTypeJsonConverter : JsonConverter<EmbeddedNoRollMoveRollType>
    {
        public override EmbeddedNoRollMoveRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "no_roll":
                    return EmbeddedNoRollMoveRollType.NoRoll;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedNoRollMoveRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedNoRollMoveRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedNoRollMoveRollType.NoRoll:
                    JsonSerializer.Serialize<string>(writer, "no_roll", options);
                    return;
            }
        }
    }
}
