// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedProgressRollMoveRollTypeJsonConverter))]
    public enum EmbeddedProgressRollMoveRollType
    {
        ProgressRoll,
    }
    public class EmbeddedProgressRollMoveRollTypeJsonConverter : JsonConverter<EmbeddedProgressRollMoveRollType>
    {
        public override EmbeddedProgressRollMoveRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "progress_roll":
                    return EmbeddedProgressRollMoveRollType.ProgressRoll;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedProgressRollMoveRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedProgressRollMoveRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedProgressRollMoveRollType.ProgressRoll:
                    JsonSerializer.Serialize<string>(writer, "progress_roll", options);
                    return;
            }
        }
    }
}
