// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleRollableColumnTextTypeJsonConverter))]
    public enum EmbeddedOracleRollableColumnTextType
    {
        OracleRollable,
    }
    public class EmbeddedOracleRollableColumnTextTypeJsonConverter : JsonConverter<EmbeddedOracleRollableColumnTextType>
    {
        public override EmbeddedOracleRollableColumnTextType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return EmbeddedOracleRollableColumnTextType.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleRollableColumnTextType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleRollableColumnTextType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleRollableColumnTextType.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
