// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedOracleTableText3OracleTypeJsonConverter))]
    public enum EmbeddedOracleTableText3OracleType
    {
        TableText3,
    }
    public class EmbeddedOracleTableText3OracleTypeJsonConverter : JsonConverter<EmbeddedOracleTableText3OracleType>
    {
        public override EmbeddedOracleTableText3OracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "table_text3":
                    return EmbeddedOracleTableText3OracleType.TableText3;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedOracleTableText3OracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedOracleTableText3OracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedOracleTableText3OracleType.TableText3:
                    JsonSerializer.Serialize<string>(writer, "table_text3", options);
                    return;
            }
        }
    }
}
