// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedMoveActionRollTypeJsonConverter))]
    public enum EmbeddedMoveActionRollType
    {
        Move,
    }
    public class EmbeddedMoveActionRollTypeJsonConverter : JsonConverter<EmbeddedMoveActionRollType>
    {
        public override EmbeddedMoveActionRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return EmbeddedMoveActionRollType.Move;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedMoveActionRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedMoveActionRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedMoveActionRollType.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
