// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(EmbeddedMoveNoRollTypeJsonConverter))]
    public enum EmbeddedMoveNoRollType
    {
        Move,
    }
    public class EmbeddedMoveNoRollTypeJsonConverter : JsonConverter<EmbeddedMoveNoRollType>
    {
        public override EmbeddedMoveNoRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return EmbeddedMoveNoRollType.Move;
                default:
                    throw new ArgumentException(String.Format("Bad EmbeddedMoveNoRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EmbeddedMoveNoRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EmbeddedMoveNoRollType.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
