// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// This type is a placeholder and may see signficant changes in v0.2.0.
    /// </summary>
    public class EntityPrompt
    {
        [JsonPropertyName("text")]
        public MarkdownString Text { get; set; }
    }
}
