// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// The version of the Datasworn format used by this data.
    /// </summary>
    [JsonConverter(typeof(ExpansionDataswornVersionJsonConverter))]
    public enum ExpansionDataswornVersion
    {
        DefaultName,
    }
    public class ExpansionDataswornVersionJsonConverter : JsonConverter<ExpansionDataswornVersion>
    {
        public override ExpansionDataswornVersion Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "0.1.0":
                    return ExpansionDataswornVersion.DefaultName;
                default:
                    throw new ArgumentException(String.Format("Bad ExpansionDataswornVersion value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, ExpansionDataswornVersion value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ExpansionDataswornVersion.DefaultName:
                    JsonSerializer.Serialize<string>(writer, "0.1.0", options);
                    return;
            }
        }
    }
}
