// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(MoveSpecialTrackRollTypeJsonConverter))]
    public enum MoveSpecialTrackRollType
    {
        SpecialTrack,
    }
    public class MoveSpecialTrackRollTypeJsonConverter : JsonConverter<MoveSpecialTrackRollType>
    {
        public override MoveSpecialTrackRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "special_track":
                    return MoveSpecialTrackRollType.SpecialTrack;
                default:
                    throw new ArgumentException(String.Format("Bad MoveSpecialTrackRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveSpecialTrackRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveSpecialTrackRollType.SpecialTrack:
                    JsonSerializer.Serialize<string>(writer, "special_track", options);
                    return;
            }
        }
    }
}
