// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(MoveNoRollType0JsonConverter))]
    public enum MoveNoRollType0
    {
        Move,
    }
    public class MoveNoRollType0JsonConverter : JsonConverter<MoveNoRollType0>
    {
        public override MoveNoRollType0 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return MoveNoRollType0.Move;
                default:
                    throw new ArgumentException(String.Format("Bad MoveNoRollType0 value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveNoRollType0 value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveNoRollType0.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
