// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A move must have this `roll_type` to receive this enhancement. This is
    /// in addition to any other restrictions made by other properties.
    /// </summary>
    [JsonConverter(typeof(MoveActionRollEnhancementRollTypeJsonConverter))]
    public enum MoveActionRollEnhancementRollType
    {
        ActionRoll,
    }
    public class MoveActionRollEnhancementRollTypeJsonConverter : JsonConverter<MoveActionRollEnhancementRollType>
    {
        public override MoveActionRollEnhancementRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "action_roll":
                    return MoveActionRollEnhancementRollType.ActionRoll;
                default:
                    throw new ArgumentException(String.Format("Bad MoveActionRollEnhancementRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveActionRollEnhancementRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveActionRollEnhancementRollType.ActionRoll:
                    JsonSerializer.Serialize<string>(writer, "action_roll", options);
                    return;
            }
        }
    }
}
