// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// An object that describes changes to a move. These changes should be
    /// applied recursively, altering only the specified properties; enhanced
    /// arrays should be concatencated with the original array value.
    /// </summary>
    public class MoveActionRollEnhancement
    {
        [JsonPropertyName("enhances")]
        public IList<AnyMoveIdWildcard> Enhances { get; set; }

        /// <summary>
        /// A move must have this `roll_type` to receive this enhancement. This
        /// is in addition to any other restrictions made by other properties.
        /// </summary>
        [JsonPropertyName("roll_type")]
        public MoveActionRollEnhancementRollType RollType { get; set; }

        [JsonPropertyName("trigger")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public TriggerActionRollEnhancement? Trigger { get; set; }
    }
}
