// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded MoveCategoryId that can be used to match multiple
    /// MoveCategory objects.
    /// </summary>
    [JsonConverter(typeof(MoveCategoryIdWildcardJsonConverter))]
    public class MoveCategoryIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MoveCategoryIdWildcardJsonConverter : JsonConverter<MoveCategoryIdWildcard>
    {
        public override MoveCategoryIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MoveCategoryIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MoveCategoryIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
