// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A progress move that rolls on a standard progress track type (defined by
    /// this move).
    /// </summary>
    [JsonConverter(typeof(MoveProgressRollRollTypeJsonConverter))]
    public enum MoveProgressRollRollType
    {
        ProgressRoll,
    }
    public class MoveProgressRollRollTypeJsonConverter : JsonConverter<MoveProgressRollRollType>
    {
        public override MoveProgressRollRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "progress_roll":
                    return MoveProgressRollRollType.ProgressRoll;
                default:
                    throw new ArgumentException(String.Format("Bad MoveProgressRollRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveProgressRollRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveProgressRollRollType.ProgressRoll:
                    JsonSerializer.Serialize<string>(writer, "progress_roll", options);
                    return;
            }
        }
    }
}
