// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A move must have this `roll_type` to receive this enhancement. This is
    /// in addition to any other restrictions made by other properties.
    /// </summary>
    [JsonConverter(typeof(MoveSpecialTrackEnhancementRollTypeJsonConverter))]
    public enum MoveSpecialTrackEnhancementRollType
    {
        SpecialTrack,
    }
    public class MoveSpecialTrackEnhancementRollTypeJsonConverter : JsonConverter<MoveSpecialTrackEnhancementRollType>
    {
        public override MoveSpecialTrackEnhancementRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "special_track":
                    return MoveSpecialTrackEnhancementRollType.SpecialTrack;
                default:
                    throw new ArgumentException(String.Format("Bad MoveSpecialTrackEnhancementRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveSpecialTrackEnhancementRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveSpecialTrackEnhancementRollType.SpecialTrack:
                    JsonSerializer.Serialize<string>(writer, "special_track", options);
                    return;
            }
        }
    }
}
