// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(MoveActionRollType0JsonConverter))]
    public enum MoveActionRollType0
    {
        Move,
    }
    public class MoveActionRollType0JsonConverter : JsonConverter<MoveActionRollType0>
    {
        public override MoveActionRollType0 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "move":
                    return MoveActionRollType0.Move;
                default:
                    throw new ArgumentException(String.Format("Bad MoveActionRollType0 value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveActionRollType0 value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveActionRollType0.Move:
                    JsonSerializer.Serialize<string>(writer, "move", options);
                    return;
            }
        }
    }
}
