// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(MoveNoRollRollTypeJsonConverter))]
    public enum MoveNoRollRollType
    {
        NoRoll,
    }
    public class MoveNoRollRollTypeJsonConverter : JsonConverter<MoveNoRollRollType>
    {
        public override MoveNoRollRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "no_roll":
                    return MoveNoRollRollType.NoRoll;
                default:
                    throw new ArgumentException(String.Format("Bad MoveNoRollRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveNoRollRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveNoRollRollType.NoRoll:
                    JsonSerializer.Serialize<string>(writer, "no_roll", options);
                    return;
            }
        }
    }
}
