// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded MoveOracleRollableId that can be used to match multiple
    /// MoveOracleRollable objects.
    /// </summary>
    [JsonConverter(typeof(MoveOracleRollableIdWildcardJsonConverter))]
    public class MoveOracleRollableIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MoveOracleRollableIdWildcardJsonConverter : JsonConverter<MoveOracleRollableIdWildcard>
    {
        public override MoveOracleRollableIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MoveOracleRollableIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MoveOracleRollableIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
