// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded MoveOracleRollableRowId that can be used to match multiple
    /// MoveOracleRollableRow objects.
    /// </summary>
    [JsonConverter(typeof(MoveOracleRollableRowIdWildcardJsonConverter))]
    public class MoveOracleRollableRowIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MoveOracleRollableRowIdWildcardJsonConverter : JsonConverter<MoveOracleRollableRowIdWildcard>
    {
        public override MoveOracleRollableRowIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MoveOracleRollableRowIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MoveOracleRollableRowIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
