// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A move must have this `roll_type` to receive this enhancement. This is
    /// in addition to any other restrictions made by other properties.
    /// </summary>
    [JsonConverter(typeof(MoveNoRollEnhancementRollTypeJsonConverter))]
    public enum MoveNoRollEnhancementRollType
    {
        NoRoll,
    }
    public class MoveNoRollEnhancementRollTypeJsonConverter : JsonConverter<MoveNoRollEnhancementRollType>
    {
        public override MoveNoRollEnhancementRollType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "no_roll":
                    return MoveNoRollEnhancementRollType.NoRoll;
                default:
                    throw new ArgumentException(String.Format("Bad MoveNoRollEnhancementRollType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, MoveNoRollEnhancementRollType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MoveNoRollEnhancementRollType.NoRoll:
                    JsonSerializer.Serialize<string>(writer, "no_roll", options);
                    return;
            }
        }
    }
}
