// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(NpcCollectionTypeJsonConverter))]
    public enum NpcCollectionType
    {
        NpcCollection,
    }
    public class NpcCollectionTypeJsonConverter : JsonConverter<NpcCollectionType>
    {
        public override NpcCollectionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "npc_collection":
                    return NpcCollectionType.NpcCollection;
                default:
                    throw new ArgumentException(String.Format("Bad NpcCollectionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, NpcCollectionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case NpcCollectionType.NpcCollection:
                    JsonSerializer.Serialize<string>(writer, "npc_collection", options);
                    return;
            }
        }
    }
}
