// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleColumnSimpleOracleTypeJsonConverter))]
    public enum OracleColumnSimpleOracleType
    {
        ColumnBasic,
    }
    public class OracleColumnSimpleOracleTypeJsonConverter : JsonConverter<OracleColumnSimpleOracleType>
    {
        public override OracleColumnSimpleOracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "column_basic":
                    return OracleColumnSimpleOracleType.ColumnBasic;
                default:
                    throw new ArgumentException(String.Format("Bad OracleColumnSimpleOracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleColumnSimpleOracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleColumnSimpleOracleType.ColumnBasic:
                    JsonSerializer.Serialize<string>(writer, "column_basic", options);
                    return;
            }
        }
    }
}
