// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleRollableTableTableText3TypeJsonConverter))]
    public enum OracleRollableTableTableText3Type
    {
        OracleRollable,
    }
    public class OracleRollableTableTableText3TypeJsonConverter : JsonConverter<OracleRollableTableTableText3Type>
    {
        public override OracleRollableTableTableText3Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleRollableTableTableText3Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleRollableTableTableText3Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleRollableTableTableText3Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleRollableTableTableText3Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
