// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleRollableTableTableTextTypeJsonConverter))]
    public enum OracleRollableTableTableTextType
    {
        OracleRollable,
    }
    public class OracleRollableTableTableTextTypeJsonConverter : JsonConverter<OracleRollableTableTableTextType>
    {
        public override OracleRollableTableTableTextType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleRollableTableTableTextType.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleRollableTableTableTextType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleRollableTableTableTextType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleRollableTableTableTextType.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
