// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableText2OracleTypeJsonConverter))]
    public enum OracleTableText2OracleType
    {
        TableText2,
    }
    public class OracleTableText2OracleTypeJsonConverter : JsonConverter<OracleTableText2OracleType>
    {
        public override OracleTableText2OracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "table_text2":
                    return OracleTableText2OracleType.TableText2;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableText2OracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableText2OracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableText2OracleType.TableText2:
                    JsonSerializer.Serialize<string>(writer, "table_text2", options);
                    return;
            }
        }
    }
}
