// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleRollableTableText2TypeJsonConverter))]
    public enum OracleRollableTableText2Type
    {
        OracleRollable,
    }
    public class OracleRollableTableText2TypeJsonConverter : JsonConverter<OracleRollableTableText2Type>
    {
        public override OracleRollableTableText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleRollableTableText2Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleRollableTableText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleRollableTableText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleRollableTableText2Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
