// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableSharedText3TypeJsonConverter))]
    public enum OracleTableSharedText3Type
    {
        OracleCollection,
    }
    public class OracleTableSharedText3TypeJsonConverter : JsonConverter<OracleTableSharedText3Type>
    {
        public override OracleTableSharedText3Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleTableSharedText3Type.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableSharedText3Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableSharedText3Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableSharedText3Type.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
