// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleColumnText2OracleTypeJsonConverter))]
    public enum OracleColumnText2OracleType
    {
        ColumnText2,
    }
    public class OracleColumnText2OracleTypeJsonConverter : JsonConverter<OracleColumnText2OracleType>
    {
        public override OracleColumnText2OracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "column_text2":
                    return OracleColumnText2OracleType.ColumnText2;
                default:
                    throw new ArgumentException(String.Format("Bad OracleColumnText2OracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleColumnText2OracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleColumnText2OracleType.ColumnText2:
                    JsonSerializer.Serialize<string>(writer, "column_text2", options);
                    return;
            }
        }
    }
}
