// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableSharedText2OracleTypeJsonConverter))]
    public enum OracleTableSharedText2OracleType
    {
        TableSharedText2,
    }
    public class OracleTableSharedText2OracleTypeJsonConverter : JsonConverter<OracleTableSharedText2OracleType>
    {
        public override OracleTableSharedText2OracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "table_shared_text2":
                    return OracleTableSharedText2OracleType.TableSharedText2;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableSharedText2OracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableSharedText2OracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableSharedText2OracleType.TableSharedText2:
                    JsonSerializer.Serialize<string>(writer, "table_shared_text2", options);
                    return;
            }
        }
    }
}
