// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Special roll instructions to use when rolling multiple times on a single
    /// oracle.
    /// </summary>
    [JsonConverter(typeof(OracleDuplicateBehaviorJsonConverter))]
    public enum OracleDuplicateBehavior
    {
        /// <summary>
        /// Duplicates results should be kept.
        /// </summary>
        Keep,

        /// <summary>
        /// Duplicate results should be kept, and they compound to make things
        /// worse.
        /// </summary>
        MakeItWorse,

        /// <summary>
        /// Duplicate results should be re-rolled.
        /// </summary>
        Reroll,
    }
    public class OracleDuplicateBehaviorJsonConverter : JsonConverter<OracleDuplicateBehavior>
    {
        public override OracleDuplicateBehavior Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "keep":
                    return OracleDuplicateBehavior.Keep;
                case "make_it_worse":
                    return OracleDuplicateBehavior.MakeItWorse;
                case "reroll":
                    return OracleDuplicateBehavior.Reroll;
                default:
                    throw new ArgumentException(String.Format("Bad OracleDuplicateBehavior value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleDuplicateBehavior value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleDuplicateBehavior.Keep:
                    JsonSerializer.Serialize<string>(writer, "keep", options);
                    return;
                case OracleDuplicateBehavior.MakeItWorse:
                    JsonSerializer.Serialize<string>(writer, "make_it_worse", options);
                    return;
                case OracleDuplicateBehavior.Reroll:
                    JsonSerializer.Serialize<string>(writer, "reroll", options);
                    return;
            }
        }
    }
}
