// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class OracleRollableTableTableTextColumnLabels
    {
        [JsonPropertyName("roll")]
        public Label Roll { get; set; }

        [JsonPropertyName("text")]
        public Label Text { get; set; }
    }
}
