// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleColumnTextOracleTypeJsonConverter))]
    public enum OracleColumnTextOracleType
    {
        ColumnText,
    }
    public class OracleColumnTextOracleTypeJsonConverter : JsonConverter<OracleColumnTextOracleType>
    {
        public override OracleColumnTextOracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "column_text":
                    return OracleColumnTextOracleType.ColumnText;
                default:
                    throw new ArgumentException(String.Format("Bad OracleColumnTextOracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleColumnTextOracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleColumnTextOracleType.ColumnText:
                    JsonSerializer.Serialize<string>(writer, "column_text", options);
                    return;
            }
        }
    }
}
