// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Provides column labels for this table. The `roll` key refers to the
    /// roll column showing the dice range (`min` and `max` on each table row).
    /// For all other column labels, see the `name` property of each child
    /// `OracleColumn`.
    /// </summary>
    public class OracleTableSharedRollsColumnLabels
    {
        [JsonPropertyName("roll")]
        public Label Roll { get; set; }
    }
}
