// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableRollableTableTextTypeJsonConverter))]
    public enum OracleTableRollableTableTextType
    {
        OracleRollable,
    }
    public class OracleTableRollableTableTextTypeJsonConverter : JsonConverter<OracleTableRollableTableTextType>
    {
        public override OracleTableRollableTableTextType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleTableRollableTableTextType.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableRollableTableTextType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableRollableTableTextType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableRollableTableTextType.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
