// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class OracleTableText3ColumnLabels
    {
        [JsonPropertyName("roll")]
        public Label Roll { get; set; }

        [JsonPropertyName("text")]
        public Label Text { get; set; }

        [JsonPropertyName("text2")]
        public Label Text2 { get; set; }

        [JsonPropertyName("text3")]
        public Label Text3 { get; set; }
    }
}
