// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTablesCollectionTypeJsonConverter))]
    public enum OracleTablesCollectionType
    {
        OracleCollection,
    }
    public class OracleTablesCollectionTypeJsonConverter : JsonConverter<OracleTablesCollectionType>
    {
        public override OracleTablesCollectionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleTablesCollectionType.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTablesCollectionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTablesCollectionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTablesCollectionType.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
