// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableSharedText2TypeJsonConverter))]
    public enum OracleTableSharedText2Type
    {
        OracleCollection,
    }
    public class OracleTableSharedText2TypeJsonConverter : JsonConverter<OracleTableSharedText2Type>
    {
        public override OracleTableSharedText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleTableSharedText2Type.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableSharedText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableSharedText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableSharedText2Type.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
