// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableRollableTableText2TypeJsonConverter))]
    public enum OracleTableRollableTableText2Type
    {
        OracleRollable,
    }
    public class OracleTableRollableTableText2TypeJsonConverter : JsonConverter<OracleTableRollableTableText2Type>
    {
        public override OracleTableRollableTableText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleTableRollableTableText2Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableRollableTableText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableRollableTableText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableRollableTableText2Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
