// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleCollectionTableSharedText3TypeJsonConverter))]
    public enum OracleCollectionTableSharedText3Type
    {
        OracleCollection,
    }
    public class OracleCollectionTableSharedText3TypeJsonConverter : JsonConverter<OracleCollectionTableSharedText3Type>
    {
        public override OracleCollectionTableSharedText3Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleCollectionTableSharedText3Type.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleCollectionTableSharedText3Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleCollectionTableSharedText3Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleCollectionTableSharedText3Type.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
