// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleCollectionTableSharedRollsTypeJsonConverter))]
    public enum OracleCollectionTableSharedRollsType
    {
        OracleCollection,
    }
    public class OracleCollectionTableSharedRollsTypeJsonConverter : JsonConverter<OracleCollectionTableSharedRollsType>
    {
        public override OracleCollectionTableSharedRollsType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleCollectionTableSharedRollsType.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleCollectionTableSharedRollsType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleCollectionTableSharedRollsType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleCollectionTableSharedRollsType.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
