// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleCollectionTableSharedText2TypeJsonConverter))]
    public enum OracleCollectionTableSharedText2Type
    {
        OracleCollection,
    }
    public class OracleCollectionTableSharedText2TypeJsonConverter : JsonConverter<OracleCollectionTableSharedText2Type>
    {
        public override OracleCollectionTableSharedText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_collection":
                    return OracleCollectionTableSharedText2Type.OracleCollection;
                default:
                    throw new ArgumentException(String.Format("Bad OracleCollectionTableSharedText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleCollectionTableSharedText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleCollectionTableSharedText2Type.OracleCollection:
                    JsonSerializer.Serialize<string>(writer, "oracle_collection", options);
                    return;
            }
        }
    }
}
