// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleTableSharedTextOracleTypeJsonConverter))]
    public enum OracleTableSharedTextOracleType
    {
        TableSharedText,
    }
    public class OracleTableSharedTextOracleTypeJsonConverter : JsonConverter<OracleTableSharedTextOracleType>
    {
        public override OracleTableSharedTextOracleType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "table_shared_text":
                    return OracleTableSharedTextOracleType.TableSharedText;
                default:
                    throw new ArgumentException(String.Format("Bad OracleTableSharedTextOracleType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleTableSharedTextOracleType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleTableSharedTextOracleType.TableSharedText:
                    JsonSerializer.Serialize<string>(writer, "table_shared_text", options);
                    return;
            }
        }
    }
}
