// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(OracleRollableTableTableText2TypeJsonConverter))]
    public enum OracleRollableTableTableText2Type
    {
        OracleRollable,
    }
    public class OracleRollableTableTableText2TypeJsonConverter : JsonConverter<OracleRollableTableTableText2Type>
    {
        public override OracleRollableTableTableText2Type Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "oracle_rollable":
                    return OracleRollableTableTableText2Type.OracleRollable;
                default:
                    throw new ArgumentException(String.Format("Bad OracleRollableTableTableText2Type value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleRollableTableTableText2Type value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case OracleRollableTableTableText2Type.OracleRollable:
                    JsonSerializer.Serialize<string>(writer, "oracle_rollable", options);
                    return;
            }
        }
    }
}
