// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(RarityTypeJsonConverter))]
    public enum RarityType
    {
        Rarity,
    }
    public class RarityTypeJsonConverter : JsonConverter<RarityType>
    {
        public override RarityType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "rarity":
                    return RarityType.Rarity;
                default:
                    throw new ArgumentException(String.Format("Bad RarityType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, RarityType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case RarityType.Rarity:
                    JsonSerializer.Serialize<string>(writer, "rarity", options);
                    return;
            }
        }
    }
}
