// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(RulesetTypeJsonConverter))]
    public enum RulesetType
    {
        Ruleset,
    }
    public class RulesetTypeJsonConverter : JsonConverter<RulesetType>
    {
        public override RulesetType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "ruleset":
                    return RulesetType.Ruleset;
                default:
                    throw new ArgumentException(String.Format("Bad RulesetType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, RulesetType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case RulesetType.Ruleset:
                    JsonSerializer.Serialize<string>(writer, "ruleset", options);
                    return;
            }
        }
    }
}
