// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectEnhancementFieldFieldTypeJsonConverter))]
    public enum SelectEnhancementFieldFieldType
    {
        SelectEnhancement,
    }
    public class SelectEnhancementFieldFieldTypeJsonConverter : JsonConverter<SelectEnhancementFieldFieldType>
    {
        public override SelectEnhancementFieldFieldType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "select_enhancement":
                    return SelectEnhancementFieldFieldType.SelectEnhancement;
                default:
                    throw new ArgumentException(String.Format("Bad SelectEnhancementFieldFieldType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectEnhancementFieldFieldType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SelectEnhancementFieldFieldType.SelectEnhancement:
                    JsonSerializer.Serialize<string>(writer, "select_enhancement", options);
                    return;
            }
        }
    }
}
