// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectValueFieldFieldTypeJsonConverter))]
    public enum SelectValueFieldFieldType
    {
        SelectValue,
    }
    public class SelectValueFieldFieldTypeJsonConverter : JsonConverter<SelectValueFieldFieldType>
    {
        public override SelectValueFieldFieldType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "select_value":
                    return SelectValueFieldFieldType.SelectValue;
                default:
                    throw new ArgumentException(String.Format("Bad SelectValueFieldFieldType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectValueFieldFieldType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SelectValueFieldFieldType.SelectValue:
                    JsonSerializer.Serialize<string>(writer, "select_value", options);
                    return;
            }
        }
    }
}
