// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SuggestionsJsonConverter))]
    public class Suggestions
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<AnyIdWildcard> Value { get; set; }
    }

    public class SuggestionsJsonConverter : JsonConverter<Suggestions>
    {
        public override Suggestions Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Suggestions { Value = JsonSerializer.Deserialize<IList<AnyIdWildcard>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Suggestions value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<AnyIdWildcard>>(writer, value.Value, options);
        }
    }
}
