// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class TagsCore
    {
        /// <summary>
        /// This object requires allies to function, and is intended for co-
        /// op play, or guided play with allies. It is not appropriate for solo
        /// play.
        /// </summary>
        [JsonPropertyName("requires_allies")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? RequiresAllies { get; set; }

        /// <summary>
        /// This object is supernatural in nature, and is ideal for settings
        /// that feature supernatural or mythic powers.
        /// </summary>
        [JsonPropertyName("supernatural")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? Supernatural { get; set; }

        /// <summary>
        /// This object is technological in nature, and is ideal for settings
        /// that feature remarkable technologies.
        /// </summary>
        [JsonPropertyName("technological")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? Technological { get; set; }
    }
}
