// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents a basic rollable oracle table with one roll column and one
    /// text result column.
    /// </summary>
    public class TruthOptionTable
    {
        /// <summary>
        /// The roll used to select a result on this oracle.
        /// </summary>
        [JsonPropertyName("dice")]
        public DiceExpression Dice { get; set; }

        [JsonPropertyName("oracle_type")]
        public TruthOptionTableOracleType OracleType { get; set; }

        /// <summary>
        /// An array of objects, each representing a single row of the table.
        /// </summary>
        [JsonPropertyName("rows")]
        public IList<OracleTableRowText> Rows { get; set; }
    }
}
