// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded TruthOptionOracleRollableId that can be used to match
    /// multiple TruthOptionOracleRollable objects.
    /// </summary>
    [JsonConverter(typeof(TruthOptionOracleRollableIdWildcardJsonConverter))]
    public class TruthOptionOracleRollableIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class TruthOptionOracleRollableIdWildcardJsonConverter : JsonConverter<TruthOptionOracleRollableIdWildcard>
    {
        public override TruthOptionOracleRollableIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new TruthOptionOracleRollableIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, TruthOptionOracleRollableIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
