// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded TruthOptionOracleRollableRowId that can be used to match
    /// multiple TruthOptionOracleRollableRow objects.
    /// </summary>
    [JsonConverter(typeof(TruthOptionOracleRollableRowIdWildcardJsonConverter))]
    public class TruthOptionOracleRollableRowIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class TruthOptionOracleRollableRowIdWildcardJsonConverter : JsonConverter<TruthOptionOracleRollableRowIdWildcard>
    {
        public override TruthOptionOracleRollableRowIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new TruthOptionOracleRollableRowIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, TruthOptionOracleRollableRowIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
