// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(TruthTypeJsonConverter))]
    public enum TruthType
    {
        Truth,
    }
    public class TruthTypeJsonConverter : JsonConverter<TruthType>
    {
        public override TruthType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "truth":
                    return TruthType.Truth;
                default:
                    throw new ArgumentException(String.Format("Bad TruthType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, TruthType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case TruthType.Truth:
                    JsonSerializer.Serialize<string>(writer, "truth", options);
                    return;
            }
        }
    }
}
